### ISSUE TITLE
Calculating tStepR

### ISSUE THREAD

**Issue by cgyurgyik** [spherical-volume-rendering/algorithm-team-collaboration#20]
https://github.com/spherical-volume-rendering/algorithm-team-collaboration/blob/8db18b6e4eff0b2cf82d3267dc3688a6a6c1c43a/polarCoordinateTraversal.m#L173

Is there a reason tStepR is calculated in the while loop rather than in ```radial_hit```?

**Comment by ak-2485** [comment]
On lines below 173 you see the update of the radial voxelID: note that this is based on comparison of an old and new radius value. Consider the [bad image URL](https://drive.google.com/open?id=1KKb8-PKp3uuTKxXDHfdn4neADZMc8C_M): you will see that as the ray travels from r1 to r2, d1>d2 and the voxelID is increasing. Similarly, as the ray travels from r3 to r4, d3<d4 and the voxelID is decreasing. Does this make sense? Can we move the radial comparisons so that they are encapsulated in radial_hit and have a return of [tStepR?](url) Maybe.

**Comment by cgyurgyik** [comment]
Addressed in #22
