### ISSUE TITLE
Spherical traversal phase

### ISSUE THREAD

**Issue by ak-2485** [spherical-volume-rendering/algorithm-team-collaboration#49]
In the spherical traversal phase, when angular and azimuthal boundaries are hit at the same time, the code currently only increments/decrements the angular voxels. An example case is given in the spherical test file. According to the logic of the traversal phase, we only enter increment/decrement phi if it is a strict minimum. Furthermore, the angular/azimuthal hit functions set tMaxTheta and tMaxPhi to inf in the case when the calculated intersection time is equal to the global time. You will see this if you add relevant print statements to the above mentioned example.

**Comment by cgyurgyik** [comment]
Ok, it may be my abuse of ```<=```. I'll look into this more.

**Comment by cgyurgyik** [comment]
https://github.com/spherical-volume-rendering/algorithm-team-collaboration/blob/4b7e66866bfac43ce287f07f79038d91cc54da5d/SphericalTraversal/sphericalCoordinateTraversal.m#L209

This may be part of the issue. :(

**Comment by ak-2485** [comment]
`else
    tStepTheta = 0;
    tMaxTheta = inf;
    if verbose
        fprintf("no hit\n")
    end
end`

**Comment by ak-2485** [comment]
No,  we don't only want to increment tMaxPhi when it is a strict minimum. We also want to increment it if it is a minimum equal to tMaxTheta or tMaxR or both.

**Comment by cgyurgyik** [comment]
![IMG_20200329_153646](https://user-images.githubusercontent.com/37983775/77858759-86b0e700-71d3-11ea-8e6b-efc8f38024d3.jpg)
Here is a crappy 2-d illustration of what I'm talking about. The ray starts in (1,2). The next traversal is a point where a radial hit and an angular hit are equal.

The algorithm will increment one on the first go, and the opposite on the second go. In the end, they both reach (2,3), just by different means. 

Since all we care about is intersection with an object in a certain voxel, this is a non-issue since we'll have to calculate the intersect math for the ray and the object anyways.

**Comment by ak-2485** [comment]
But that can't happen for the case when we have an angular and azimuthal step that happen simultaneously: if they both should increment at t=6, say theta increments first, then the global time is set to 6. At the next iteration, phi won't increment because tMaxPhi is set to inf.

**Comment by ak-2485** [comment]
Similarly, for the 2D case, if at t = 10 we should increment R and Theta but R is incremented first, at the next iteration the global time will be equal to tMaxTheta and tMaxTheta will be set to inf instead of incrementing.

**Comment by cgyurgyik** [comment]
Yep and that's how our algorithm differs from the A&W. Thanks for clarifying. I'm going to leave this unclosed for now so I can look back at it.
